#colors:
#  cursor:
#    text: CellBackground
#    cursor: CellForeground
## LIGHT
##  primary:
##    background: '0xffffff'
##    foreground: '0x3c3836'
##  normal:
##    black:   '0xfbf1c7'
##    red:     '0xcc241d'
##    green:   '0x98971a'
##    yellow:  '0xd79921'
##    blue:    '0x458588'
##    magenta: '0xb16286'
##    cyan:    '0x689d6a'
##    white:   '0x7c6f64'
##  bright:
##    black:   '0x928374'
##    red:     '0x9d0006'
##    green:   '0x79740e'
##    yellow:  '0xb57614'
##    blue:    '0x076678'
##    magenta: '0x8f3f71'
##    cyan:    '0x427b58'
##    white:   '0x3c3836'
## DARK
#  primary:
#    background: '0x000000'
#    foreground: '0xebdbb2'
#  normal:
#    black:   '0x282828'
#    red:     '0xcc241d'
#    green:   '0x98971a'
#    yellow:  '0xd79921'
#    blue:    '0x458588'
#    magenta: '0xb16286'
#    cyan:    '0x689d6a'
#    white:   '0xa89984'
#  bright:
#    black:   '0x928374'
#    red:     '0xfb4934'
#    green:   '0xb8bb26'
#    yellow:  '0xfabd2f'
#    blue:    '0x83a598'
#    magenta: '0xd3869b'
#    cyan:    '0x8ec7c'
#    white:   '0xebdbb2'
#
#  indexed_colors:
#    - { index: 16, color: '0xdc9656' }
#    - { index: 17, color: '0xa16946' }
#    - { index: 18, color: '0x282828' }
#    - { index: 19, color: '0x383838' }
#    - { index: 20, color: '0xb8b8b8' }
#    - { index: 21, color: '0xe8e8e8' }
#
#  selection:
#    text: '0xffffff'
#    background: '0xdc3232'
#    white:   '0xffffff'
colors:
  cursor:
    text: CellBackground
    cursor: CellForeground
# Hepburn
  primary:
    background: '#000000'
    foreground: '#fbf1c7'
  normal:
    black:   '#282828'
    red:     '#cc241d'
    green:   '#98971a'
    yellow:  '#d79921'
    blue:    '#458588'
    magenta: '#b16286'
    cyan:    '#689d6a'
    white:   '#a89984'
  bright:
    black:   '#928374'
    red:     '#fb4934'
    green:   '#b8bb26'
    yellow:  '#fabd2f'
    blue:    '#83a598'
    magenta: '#d3869b'
    cyan:    '#8ec07c'
    white:   '#ebdbb2'

  indexed_colors:
    - { index: 16, color: '#dc9656' }
    - { index: 17, color: '#a16946' }
    - { index: 18, color: '#282828' }
    - { index: 19, color: '#383838' }
    - { index: 20, color: '#b8b8b8' }
    - { index: 21, color: '#e8e8e8' }

  selection:
    text: '#ffffff'
    background: '#dc3232'
    white:   '#ffffff'
