#-- Homebrew
if [[ $(command -v /opt/homebrew/bin/brew) != "" ]] then
    eval $(/opt/homebrew/bin/brew shellenv)
    #-- homebrew complition
    FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"
fi

export PATH=$GOROOT/bin:$GOPATH/bin:$PATH

#-- Zsh
export HISTFILE="$XDG_STATE_HOME"/zsh/history

#-- sorce work zsh files
for rcfile in /Users/metalhead/Github/office/$WORK/config/zsh/*; do
  source $rcfile
done
