#-- Homebrew
if [[ $(command -v /opt/homebrew/bin/brew) != "" ]] then
    eval $(/opt/homebrew/bin/brew shellenv)
fi

#-- Zsh
export HISTFILE="$XDG_STATE_HOME"/zsh/history

#source $ZDOTDIR/work/kreditbee/zsh/env.zsh
