#-- ATOM -------------------------------------------------------------------------------------------
export ATOM_HOME="$XDG_DATA_HOME"/atom

#-- AWS --------------------------------------------------------------------------------------------
export AWS_SHARED_CREDENTIALS_FILE="$XDG_CONFIG_HOME/aws/credentials"
export AWS_CONFIG_FILE="$XDG_CONFIG_HOME/aws/config"

#-- BASH -------------------------------------------------------------------------------------------
## bash completion
export BASH_COMPLETION_USER_FILE="$XDG_CONFIG_HOME"/bash-completion/bash_completion

#-- CARGO ------------------------------------------------------------------------------------------
export CARGO_HOME="$XDG_DATA_HOME"/cargo

#-- DOCKER -----------------------------------------------------------------------------------------
export DOCKER_CONFIG="$XDG_CONFIG_HOME"/docker
export MACHINE_STORAGE_PATH="$XDG_DATA_HOME"/docker-machine

#-- ECLIPSE ----------------------------------------------------------------------------------------
## Option -Dosgi.configuration.area=@user.home/.config/.. overrides but must be added to "$ECLIPSE_HOME"/eclipse.ini" rather than command line which means you must have write access to $ECLIPSE_HOME. (Arch Linux hard-codes $ECLIPSE_HOME in /usr/bin/eclipse)

#-- GOLANG -----------------------------------------------------------------------------------------
export GOPATH="$XDG_DATA_HOME"/go
if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    export GOROOT="/usr/local/go"
elif [[ "$OSTYPE" == "darwin"* ]]; then
    if [[ -z "${GOROOT}" ]]; then
        # export GOROOT="/opt/homebrew/Cellar/go/1.18/libexec"
        export GOROOT="/opt/homebrew/opt/go@1.17/libexec"
    fi
fi

#-- JAVA  ------------------------------------------------------------------------------------------
## Java#OpenJDK
export _JAVA_OPTIONS=-Djava.util.prefs.userRoot="$XDG_CONFIG_HOME"/java
export _JAVA_OPTIONS=-Djava.util.prefs.userRoot="$XDG_CONFIG_HOME"/java

#-- LESS -------------------------------------------------------------------------------------------
export LESSKEY="$XDG_CONFIG_HOME"/less/lesskey
export LESSHISTFILE=$XDG_CACHE_HOME/less/history

#-- Make -------------------------------------------------------------------------------------------
if [[ $(command -v /opt/homebrew/bin/brew) != "" ]] then
    export _MAKE="/opt/homebrew/opt/make/libexec/gnubin"
fi

#-- MANPAGER ---------------------------------------------------------------------------------------
#export MANPAGER='nvim +Man!'

#-- MYSQL ------------------------------------------------------------------------------------------
# ~/.my.cnf only supported for mysql-server, not mysql-client ## ~/.mylogin.cnf unsupported
export MYSQL_HISTFILE=$XDG_DATA_HOME/mysql_history

#-- NODE -------------------------------------------------------------------------------------------
## node.js
export NODE_REPL_HISTORY=$XDG_DATA_HOME/node_repl_history
export NPM_CONFIG_USERCONFIG=$XDG_CONFIG_HOME/npm/npmrc

#-- NVM --------------------------------------------------------------------------------------------
export NVM_DIR="$XDG_DATA_HOME/nvm"

#-- PYTHON -----------------------------------------------------------------------------------------
export AZURE_CONFIG_DIR=$XDG_DATA_HOME/azure
export GRIPHOME="$XDG_CONFIG_HOME/grip"
export PYLINTHOME="$XDG_CACHE_HOME"/pylint
export PYTHON_EGG_CACHE="$XDG_CACHE_HOME"/python-eggs

##-- REDIS ------------------------------------------------------------------------------------
export REDISCLI_HISTFILE="$XDG_DATA_HOME"/redis/rediscli_history
export REDISCLI_RCFILE="$XDG_CONFIG_HOME"/redis/redisclirc

#-- RUBY -------------------------------------------------------------------------------------------
## Ruby#Bundler
export BUNDLE_USER_CONFIG="$XDG_CONFIG_HOME"/bundle
export BUNDLE_USER_CACHE="$XDG_CACHE_HOME"/bundle
export BUNDLE_USER_PLUGIN="$XDG_DATA_HOME"/bundle

## Ruby#RubyGems
export GEM_HOME="$XDG_DATA_HOME"/gem
export GEM_SPEC_CACHE="$XDG_CACHE_HOME"/gem

#-- RUST -------------------------------------------------------------------------------------------
## Rust#Rustup
export RUSTUP_HOME="$XDG_DATA_HOME"/rustup

##-- TermInfo -------------------------------------------------------------------------------
export TERMINFO="$XDG_DATA_HOME"/terminfo
export TERMINFO_DIRS="$XDG_DATA_HOME"/terminfo:/usr/share/terminfov

##-- VirtualENV -------------------------------------------------------------------------------
export WORKON_HOME="$XDG_DATA_HOME/virtualenvs"

##-- Vscode -----------------------------------------------------------------------------------
export VSCODE_PORTABLE="$XDG_DATA_HOME/vscode"

#-- WORK -------------------------------------------------------------------------------------------
export WORK=krazybee

